source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

platform :ios, '11.0'

target 'AdmobDemo_Example' do
  pod 'AdmobDemo', :path => '../'
  
  pod 'Google-Mobile-Ads-SDK'
  
  pod 'MentaBaseGlobal', '1.0.0'
  pod 'MentaMediationGlobal', '1.0.0'
  pod 'MentaVlionGlobal', '1.0.0'
  pod 'MentaVlionGlobalAdapter', '1.0.0'
    
  target 'AdmobDemo_Tests' do
    inherit! :search_paths

    
  end
end
