source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

platform :ios, '12.0'

target 'AdmobDemo_Example' do
  pod 'GoogleMobileAdsMediationMenta', :path => '../'
  
  target 'AdmobDemo_Tests' do
    inherit! :search_paths

    
  end
end
